---
- hosts: localhost
  become: true
  become_user: ketan
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/home/ketan/ansible.txt"
      state: touch

  - name: Ansible create file with content example
    copy:
      dest: "/home/ketan/ansible.txt"
      content: |
        cat
        dog
        tiger

  - name: Ansible create new file with permissions example.
    file:
      path: "/home/ketan/ansible.txt"
      state: touch
      mode: 0777
      owner: ketan

  - name: Ansible create multiple files example
    file:
      path: "{{ item }}"
      state: touch
      mode: 0775
    with_items:
    - /home/ketan/a.txt
    - /home/ketan/b.txt
    - /home/ketan/c.txt
    - /home/ketan/d.txt

  - name: Ansible create multiple files example
    file:
      path: "{{ item.location }}"
      state: touch
      mode: "{{ item.mode }}"
    with_items:
    - { location: '/home/ketan/x.txt',mode: '0644'}
    - { location: '/home/ketan/y.txt',mode: '0755'}

  - name: Ansible replace string example
    replace:
      dest: /home/ketan/ansible.txt
      regexp: 'cat'
      replace: "world"

  - name: Ansible replace multiple words example
    replace:
      dest: /home/ketan/ansible.txt
      regexp: "{{ item}}"
      replace: "lion"
    with_items:
    - 'world'
    - 'dog'

  - name: Ansible multiple replace example
    replace:
      dest: "{{ item.dest }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { dest: '/home/ketan/ansible.txt', regexp1: 'lion', replace: 'chair'}
      - { dest: '/home/ketan/ansible.txt', regexp1: 'tiger', replace: 'table'}

  - name: Ansible remove words example
    replace:
      dest: "/home/ketan/ansible.txt"
      regexp: "table"
