---
- hosts: localhost
  become: true
  become_user: ketan
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/home/ketan/ansible.txt"
      state: touch

  - name: Ansible create file with content example
    copy:
      dest: "/home/ketan/ansible.txt"
      content: |
        cat
        dog
        tiger

  - name: Ansible create new file with permissions example.
    file:
      path: "/home/ketan/ansible.txt"
      state: touch
      mode: 0777
      owner: ketan

  - name: Ansible create multiple files example
    file:
      path: "{{ item }}"
      state: touch
      mode: 0775
    with_items:
    - /home/ketan/a.txt
    - /home/ketan/b.txt
    - /home/ketan/c.txt
    - /home/ketan/d.txt

  - name: Ansible create multiple files example
    file:
      path: "{{ item.location }}"
      state: touch
      mode: "{{ item.mode }}"
    with_items:
    - { location: '/home/ketan/x.txt',mode: '0644'}
    - { location: '/home/ketan/y.txt',mode: '0755'}

  - name: Ansible replace string example
    replace:
      dest: /home/ketan/ansible.txt
      regexp: 'cat'
      replace: "world"

  - name: Ansible replace multiple words example
    replace:
      dest: /home/ketan/ansible.txt
      regexp: "{{ item}}"
      replace: "lion"
    with_items:
    - 'world'
    - 'dog'

  - name: Ansible multiple replace example
    replace:
      dest: "{{ item.dest }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { dest: '/home/ketan/ansible.txt', regexp1: 'lion', replace: 'chair'}
      - { dest: '/home/ketan/ansible.txt', regexp1: 'tiger', replace: 'table'}

  - name: Ansible remove words example
    replace:
      dest: "/home/ketan/ansible.txt"
      regexp: "table"

  - name: Ansible check file exists example.
    stat:
      path: /home/ketan/ansible.txt
    register: file_details

  - debug:
      msg: " The file or directory exists "
    when: file_details.stat.exists

  - debug:
      msg: " The file or directory exists "
    when: file_details.stat.exists and file_details.stat.isreg

  - debug:
      msg: " The file or directory exists "
    when: file_details.stat.exists and file_details.stat.isdir == false and file_details.stat.islnk == false

  - name: Ansible check directory exists example.
    stat:
      path: /home/ketan/google
    register: files_to_delete

  - debug:
      msg: "It is a directory"
    when: files_to_delete.stat.exists and files_to_delete.stat.isdir

  - name: ansible create directory example
    file:
      path: /home/ketan/google
      state: directory

  - name: ansible create directory with mode setting example
    file:
      path: /home/ketan/google
      state: directory
      mode: "u=rw,g=wx,o=rwx"

  - name: ansible set permission recursvely for a directory
    file:
      path: /home/ketan/google
      state: directory
      mode: "u=rw,g=wx,o=rwx"
      recurse: yes

  - name: ansible create multiple directory example
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - '/home/ketan/google1'
      - '/home/ketan/google2'
      - '/home/ketan/google3'

  - name: ansible create directory with_items example
    file:
      path: "{{ item.dest }}"
      mode: "{{item.mode}}"
      state: directory
    with_items:
      - { dest: '/home/ketan/google4', mode: '0777'}
      - { dest: '/home/ketan/google5', mode: '0707'}
      - { dest: '/home/ketan/google6', mode: '0575'}

  - name: ansible create local directory example
    local_action:
      module: file
      path: /tmp/local_file
      state: directory

  - name: ansible set permission recursvely for a directory
    file:
      path: "/tmp/devops_directory{{ansible_date_time.date}}"
      state: directory
      mode: "u=rw,g=wx,o=rwx"
      recurse: yes

  - name: ansible remove directory example
    file:
      path: /home/ketan/google
      state: absent
