---

- hosts: localhost
  become: true
  become_user: ketan

  tasks:

  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/home/ketan"
    register: find_output

  - debug:
      var: find_output

  - debug:
      msg: "{{ find_output }}"

  - debug:
      var: "{{ find_output.stdout }}"
